# Generated by Django 4.2.13 on 2024-09-02 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app2", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="capturedphoto",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="capturedphoto",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="capturedphoto",
            name="photo",
            field=models.ImageField(upload_to="captured_photos/"),
        ),
        migrations.AlterField(
            model_name="capturedphoto",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
