# Generated by Django 4.2.16 on 2024-09-05 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app2", "0003_saveimage_alter_capturedphoto_photo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="saveimage",
            old_name="name",
            new_name="latitude",
        ),
        migrations.AddField(
            model_name="saveimage",
            name="location",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="saveimage",
            name="longitude",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
