# Generated by Django 4.2.16 on 2024-09-05 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app2", "0004_rename_name_saveimage_latitude_saveimage_location_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="saveimage",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="saveimage",
            name="location",
        ),
        migrations.RemoveField(
            model_name="saveimage",
            name="longitude",
        ),
    ]
